# Generated by Django 6.0.4 on 2026-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_nd_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
